apiVersion: v1
kind: Service
metadata:
  name: flaskapi-service
  namespace: flaskapi
spec:
  type: NodePort
  selector:
    app: flaskapi
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30000